# Generated by Django 2.2.6 on 2019-10-16 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umiyama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmaapage',
            name='maa_image',
            field=models.ForeignKey(help_text='Please select the Image ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
    ]
